### ISSUE TITLE
Fail to upload the agreement

### ISSUE THREAD

**Issue by wang101** [paip-2019/challenge#17]
Hi. I fail to open the form directed by step 3 "Return THE SIGNED AGREEMENT by uploading on _here_". It shows:

>  Your trial period has expired. Please buy a license to continue using the file upload form.
> For assistance, please email us or send a tweet @labnol

Thanks.

**Comment by wisepaip** [comment]
Thank you for contacting us about the error. I am sorry for the inconvenience.

We found the problem with uploading files. Our team is working through to resolve the issue.
Temporarily we've decided to get the data agreement via e-mail.
**Please return your Signed Agreement to e-mail, wiseapaip@gmail.com**

Thank you again for bringing the issue to our attention.

**Comment by wang101** [comment]
Thanks for your prompt reply. 😄

**Comment by tomiesm** [comment]
e-mail does not work because it does not exist:

wiseapaip@gmail.com
gmail-smtp-in.l.google.com
Remote Server returned '554 5.1.1 <gmail-smtp-in.l.google.com #5.1.1 smtp; 550-5.1.1 **The email account that you tried to reach does not exist.** Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 https://support.google.com/mail/?p=NoSuchUser w17si78479ejb.171 - gsmtp>'

**Comment by wisepaip** [comment]
We filx the uploading page. Please visit [here](https://script.google.com/macros/s/AKfycbywNr3yPC41Yv_AiUxWG2eTnqVsebaV-hhoF-6GkCujloVjMp8/exec)!

**Comment by wisepaip** [comment]
> e-mail does not work because it does not exist:
> 
> [wiseapaip@gmail.com](mailto:wiseapaip@gmail.com)
> gmail-smtp-in.l.google.com
> Remote Server returned '554 5.1.1 <gmail-smtp-in.l.google.com #5.1.1 smtp; 550-5.1.1 **The email account that you tried to reach does not exist.** Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 https://support.google.com/mail/?p=NoSuchUser w17si78479ejb.171 - gsmtp>'

My apology! Our e-mail address is wisepaip@gmail.com
