### ISSUE TITLE
Regarding Viable tumor

### ISSUE THREAD

**Issue by AshStuff** [paip-2019/challenge#19]
Hello,
What does the inner circle mean for the green line ? 
I know it belongs to Whole tumor but do we have to consider the inner circle as a viable tumor? 

<img width="758" alt="Screen Shot 2019-04-18 at 10 36 12 PM" src="https://user-images.githubusercontent.com/9457497/56404251-32636000-622b-11e9-8cbc-c9fbbd292621.png">

**Comment by wisepaip** [comment]
Hello,
Thank you for asking. That's a good question.

There are **2 regions** you should ignore on viable tumor area.
 
(a) **the white background regions** should be ignored.
:  Please check the baseline from our [data description.](https://paip2019.grand-challenge.org/Dataset/) 

> As with all digital pathology data, the annotation labels provided are bound to have some level of errors. To minimize this error, we empirically set RGB 235, 210, 235 to a threshold value, and only pixels with values so that the pixels below the threshold was recognized as ‘tissue’. On the other hand, there are numerous 'holes' in the 'tissue' area, and it is impossible to process them on a single perfect basis. So when we did threshold processing, we decided to handle only tissue OUTLINES, unless there was an expert annotation. In other words, background white detected within the tissue area was ignored unless pathologists added any marking. We clarify this process and leave it to the creativity of the participants on how to handle the resolution limitations of these pathology annotation data.  

**(b) Negative pen region:**

In the XML annotation file of its corresponding SVS image, **NegativeROA="1"** should be ignored in the calculation of the tumor burden.
The dotted green line presents the negative pen region in the SVS image.

**Comment by newhyun00** [comment]
Hello,

I am bit confused after reading your answer

It is clear that the white background region should be ignored when calculating the viable tumor burden
However, why should we also ignore the dotted green line (negative pen region?) ?

According to the Data Description on the PAIP2019 challenge, 
Viable tumor burden = Viable Tumor Area (enclosed green region) / Whole Tumor Area (enclosed yellow region)

If the dotted green line equals to "NegativeROA=1", area enclosed by the dotted green line should be included in the tumor burden calculation

I would appreciate it if you can clarify this one more time

Thank you

**Comment by wisepaip** [comment]
Thank you for the question. 
We haven't mentioned the **'Negative Pen Region'** on our data description. We will add the explanation on [PAIP 2019 Challenge](https://paip2019.grand-challenge.org/Dataset/). 

<1> I would like to clarify that **XML FIle is only for the reference** and is not the ground truth. An image mask we've provided as TIF file is the ground truth. 
**We've excluded two regions (white background regions & negative pen regions) on the TIF file.**

<2> **Negative pen region** means **designated areas not to analyze by the pathologist.**
The green line which is defined as a viable tumor should be included in the tumor burden calculation. 
 Negative Pen Region, NegativeROA="1" on XML file should be ignored in the calculation of the tumor burden. We've excluded the negative pen region on the TIF file.

There are three regions in the XML annotation file of its corresponding SVS image.
- Yellow Line: The Annotation id ="1", **NegativeROA="0"** denote the Entire Tumor Area
- Green Line: The Annotation id = "2", **NegativeROA="0**" denotes the Viable Tumor Area
- Green Dotted(Dashed) Line: The Annotation id ="2", **NegativeROA ="1**" denotes the Negative Pen Region


<3> Depending on which image viewer you use, the color of the line and shape could be varied. 
Since our whole slide images were scanned and annotated by Aperio, you'll find[ ImageScope](https://www.leicabiosystems.com/digital-pathology/manage/aperio-imagescope/) software is [usefu](https://github.com/paip-2019/challenge/issues/16#issuecomment-48399017)l to read SVS. 
It seems ASAP viewer doesn't display the Negative Pen region.

**Comment by newhyun00** [comment]
Thank you for the clarification!
It seems I was confused between the Green solid line and dotted line
