### ISSUE TITLE
Image Annotation

### ISSUE THREAD

**Issue by tianmaliuixing** [paip-2019/challenge#23]
Dear PAIP organizers,
       Thank you very much for providing such valuable data!
       Could you explain how you marked the lesions? I found the image annotation details were not very good, especially the border.

**Comment by jinsamdol** [comment]
Hello @tianmaliuixing !
Thank you for your interest in our challenge.
Our main member who can ask your question is currently on vacation, thus we would afford more information on this issue after this coming Monday.

**Comment by wisepaip** [comment]
@tianmaliuixing, Thank you for your patience.

In my understanding, your question is about the whole tumor area boundary (yellow line) annotation policy, right?

### Definition of the tumor area
> Entire tumor area is defined as **_the outermost boundary_** enclosing all dispersed viable tumor cell nests, tumor necrosis, and tumor capsule one file holds one whole tumor area.

### **The outermost boundary** defined by the pathologist as follows:
- The entire tumor boundary is the line of the border between the non-tumor area and the tumor area. 
- The border of the entire tumor was drawn at the border of the tumor capsule. The tumor capsule may or may not contain tumor cells.
- The pathologist marked on the outermost boundary of the viable tumor area when the border between the non-tumor area and tumor area is unclear.

We understand the annotation labels provided are bound to have some level of errors. To minimize error we've provided as TIF files for the ground truth. Please check the Image Mask and use the XML FIle as only for the reference.

**Comment by tianmaliuixing** [comment]
@wisepaip , Thanks for your reply. 
Can I understand that the tif file is more accurate and can be used as a mask to train the model. The XML file is for reference only, or it can be completely used without the XML file?
One more question, did you use the traditional algorithm to mark out the general area and then let the experts correct it?

**Comment by hjoonjang** [comment]
@tianmaliuixing ,
You can consider the XML files as 'preliminary' annotations, which might be utilized as ground-truth just by your preference, possibly, not preferably. In contrast, you would consider the tif files as refined annotations, which certainly are basic ground-truth we strongly recommend the participants to use. Again, the tif binary mask is a preprocessed version of the original XML annotation so that the unnecessary background pixels are removed as much as possible. The preprocessing procedures are described [here](https://paip2019.grand-challenge.org/Dataset/), but I found something minor is missing. We will check the description and amend it soon.

For the additional question, we did not apply any computational algorithm at first. In other words, the experts have drawn all the annotations from scratch, and then the background-removing process follows.

I hope this can make them clear.
Thank you for your active participation.

**Comment by tianmaliuixing** [comment]
@hjoonjang Thank you very much for your patient reply, I get it.
