### ISSUE TITLE
Test data problem

### ISSUE THREAD

**Issue by tianmaliuixing** [paip-2019/challenge#41]
Dear PAIP organizers,
         We downloaded the test data and found that there were about ten pieces of data very different from the previous training data. Then, we want to know if this is what we need to do algorithmic processing, or if this is the wrong data.
         Here are some visualizations:
![sample](https://user-images.githubusercontent.com/11666931/64149938-c8ee9180-ce59-11e9-99fb-242d486de14e.jpg)
         Looking forward to receiving your reply. 
Thanks.

**Comment by jjhjhj69** [comment]
Dear organizers.
In addition to the above issue, I have encountered problems with test slides 01_01_0176.svs when attempting to read_region with openslide. The error is the following.
=======================================================
TIFFFillTile: 0: Invalid tile byte count, tile 216.
Traceback (most recent call last):
  File "Untitled-1.py", line 6, in <module>
    img = slide.read_region((0,0),2,slide.level_dimensions[0])
  File "/home/jaehoon/.conda/envs/pytorch/lib/python3.7/site-packages/openslide/__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "/home/jaehoon/.conda/envs/pytorch/lib/python3.7/site-packages/openslide/lowlevel.py", line 259, in read_region
    _read_region(slide, buf, x, y, level, w, h)
  File "/home/jaehoon/.conda/envs/pytorch/lib/python3.7/site-packages/openslide/lowlevel.py", line 196, in _check_error
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: TIFFRGBAImageGet failed
=========================================================
Please check if this slide is correct. Thank you.

**Comment by hjoonjang** [comment]
Hi, @tianmaliuixing
Considering the blank parts of the slides, I'd experienced those errors with ```openslide``` package when I tried to extract tiles from non-zero zoom level. Since then I've preferred ```pyvips``` package to load slide images. On the other hand, if you are curious about the difference between surgery and biopsy slides, we will provide more details of them as soon as possible. (Basically, it's not much different in the viewpoint of the image processing.)

Thanks,

**Comment by tianmaliuixing** [comment]
Hi, @hjoonjang 
Similar to the all-black area in slide, I can deal with it, but I would like to know whether the section numbered 171-179 is normal or not. The picture is shown in figure 01_01_01_0171 above.
Thanks.

**Comment by hjoonjang** [comment]
Hi, @jjhjhj69 
Thanks for giving the details of your errors.

Could you please try to extract them int tile by tile manner? If you met those errors specifically on slide #176, I guess that might be because it is a much larger slide than others, so that your code may have troubles just like when you try to load level0 image at once with ```read_region``` method. (Or, could you please try ```slide.level_dimensions[2]``` to match the size with level2?)

If everything lets you down, then I would recommend you to use ```pyvips``` package to load images because it's much more convenient especially in this case.

**Comment by hjoonjang** [comment]
@tianmaliuixing 
We will provide detailed explanations about those data soon. By the way, those slides, which are instances called *Biopsy* slides, are intentionally included, and it's certainly not errors.

**Comment by tianmaliuixing** [comment]
@hjoonjang 
Ok, thanks a lot! We'll take a good look at it.

**Comment by wisepaip** [comment]
As @hjoonjang mentioned above, 171 case is not the error. 
They're the cases with liver biopsy specimen.
