### ISSUE TITLE
Can't submit test results

### ISSUE THREAD

**Issue by SeyedAlirezaFatemi** [paip-2019/challenge#43]
Hi.
On the submission page when we push the 'Choose file' button and select the prediction file, nothing happens. What is the problem?

**Comment by hjoonjang** [comment]
Hi, @SeyedAlirezaFatemi 
We've never seen that kind of error. It should show you a progress bar immediately though it takes a while to be filled. Could you try again after pushing Ctrl+F5 to refresh the page? Please let us know if you continue to be bothered after retry so that we report this case to Grand-challenge platform developers. (Then please provide some detailed information of your system; OS, browser, size of the submission zip file, and so on.)

Thanks.
