### ISSUE TITLE
Have the top 10 been announced?

### ISSUE THREAD

**Issue by yangsenwxy** [paip-2019/challenge#47]
Dear PAIP organizers,
       If you do not receive the email, it means you have not entered the top 10？

**Comment by haranrk** [comment]
@hjoonjang @wisepaip 
Is there any update with regards to when the results will be announced?

**Comment by ysssgdhr** [comment]
Wonder when the results will be announced , too

**Comment by wisepaip** [comment]
We're going to do our best to have the result out in this week.
We start to evaluate the result this week since we had a national holiday last week. 
Also, we're thoroughly checking for overlapping submissions and participant lists, so this is delaying the announcement too. 
Thank you so much for taking part in the challenge. We will update you very soon.

**Comment by SeyedAlirezaFatemi** [comment]
Hello. Any news on the results?

**Comment by wisepaip** [comment]
@SeyedAlirezaFatemi Thank you for your patience. We've sent e-mail to participants who have submitted the results.  Please check your e-mail. Thank you.
