### ISSUE TITLE
validation images ground truth

### ISSUE THREAD

**Issue by codeskings** [paip-2019/challenge#51]
Dears, thank you for granting us the ability to process this high quality images. I have an issue , when I try to convert the the xml files of the validation images into binary masks using the provided code, I got a bulky mask with no fine details as the one shown when opening the xml file along with the svs file. Also, I found in the download website this note " We would like to clarify that XML File is only for the reference and is not the ground truth. Image masks we've provided as TIF files are the ground truth.". In this case how am I supposed to obtain the accurate ground truth annotations of these validation images? Thank you

**Comment by Paip-2020** [comment]
Can you check if 2 layers are present (whole and viable) using svs viewer like ASAP(https://computationalpathologygroup.github.io/ASAP/)?
It seems like while generating binary mask, annotation id 1 (whole) is generated but annotation id 2 (viable) mask is missing. If you cannot figure out the problem, please send us the conversion code you used.

For evaluation, we compare the result with the ground truth as pixel-wise. Which means XML file is for reference, and the generated binary mask is used for actual evaluation. However, since binary mask is obtained from the XML data, we can say that XML is post-processed as binary mask for evaluation.

If you have further questions, please email us at paip.challenge@gmail.com

Thanks,

**Comment by codeskings** [comment]
Really appreciate your reply and help. Yes, this was the issue I was generating the mask for the whole tumor area and not the viable. Thank you
